name = "cellphones-crawler"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "cellphones-db"
database_id = "YOUR_DATABASE_ID_HERE"
